import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const external = [
	'obsidian',
	'electron',
	'@codemirror/autocomplete',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	...builtinModules,
];

const jsContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external,
	format: 'cjs',
	charset: 'utf8',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	// Keep actionable warnings/errors, but remove development chatter in releases.
	pure: prod ? ['console.log', 'console.debug'] : [],
	legalComments: 'none',
});

const cssContext = await esbuild.context({
	entryPoints: ['src/styles.css'],
	bundle: true,
	charset: 'utf8',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	outfile: 'styles.css',
	minify: prod,
	legalComments: 'none',
});

if (prod) {
	await Promise.all([jsContext.rebuild(), cssContext.rebuild()]);
	await Promise.all([jsContext.dispose(), cssContext.dispose()]);
} else {
	await Promise.all([jsContext.watch(), cssContext.watch()]);
}
