import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const external = [
	'obsidian',
	'electron',
	'@codemirror/autocomplete',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	...builtinModules,
];

const jsContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external,
	format: 'cjs',
	charset: 'utf8',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	// Keep actionable warnings/errors, but remove development chatter in releases.
	pure: prod ? ['console.log', 'console.debug'] : [],
	legalComments: 'none',
});

const cssContext = await esbuild.context({
	entryPoints: ['src/styles.css'],
	bundle: true,
	charset: 'utf8',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	outfile: 'styles.css',
	minify: prod,
	legalComments: 'none',
});

if (prod) {
	await Promise.all([jsContext.rebuild(), cssContext.rebuild()]);
	await Promise.all([jsContext.dispose(), cssContext.dispose()]);
} else {
	await Promise.all([jsContext.watch(), cssContext.watch()]);
}

// Ship the hot-reloadable model_matrix.json next to main.js so the
// NativeAutoRouter can read it at runtime via the Obsidian vault adapter
// (no fs/child_process in routing logic — Obsidian compliance preserved).
{
	const here = dirname(fileURLToPath(import.meta.url));
	const src = join(here, 'src', 'config', 'model_matrix.json');
	const dest = join(here, 'model_matrix.json');
	if (existsSync(src)) {
		mkdirSync(dirname(dest), { recursive: true });
		copyFileSync(src, dest);
	}
}
